set -x
set -e
# #define HAL_SRAM_MODULE_ENABLED, I2C

mkdir -p build
INC="-I STM32/STM32H5xx_HAL_Driver/Inc/ -I . -I STM32/CMSIS/Core/Include -I STM32 -I STM32/BSP/STM32H573I-DK -I STM32/BSP/Components -I STM32/BSP/Components/Common -I STM32/CMSIS/Device/ST/STM32H5xx/Include/ -I STM32/CMSIS/Include/"
#  -D __ASSERT_FUNC=ahoj
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_cortex.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_cortex.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_dma.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_dma.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_dma_ex.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_dma_ex.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_exti.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_exti.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_flash.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_flash.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_flash_ex.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_flash_ex.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_gpio.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_gpio.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_icache.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_icache.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pwr.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_pwr.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pwr_ex.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_pwr_ex.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rcc.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_rcc.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rcc_ex.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_rcc_ex.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_sram.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_sram.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_i2c.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_i2c.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_i2c_ex.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_i2c_ex.o"
#arm-none-eabi-gcc "STM32/STM32H5xx_HAL_Driver/Src/stm32h5xx_ll_fmc.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_ll_fmc.o"
#arm-none-eabi-gcc "STM32/system_stm32h5xx.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/system_stm32h5xx.o"
#arm-none-eabi-gcc "STM32/BSP/STM32H573I-DK/stm32h573i_discovery.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h573i_discovery.o"
#arm-none-eabi-gcc "STM32/BSP/STM32H573I-DK/stm32h573i_discovery_lcd.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h573i_discovery_lcd.o"
#arm-none-eabi-gcc "STM32/BSP/STM32H573I-DK/stm32h573i_discovery_ts.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h573i_discovery_ts.o"
#arm-none-eabi-gcc "STM32/BSP/STM32H573I-DK/stm32h573i_discovery_bus.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h573i_discovery_bus.o"
#arm-none-eabi-gcc "STM32/Utilities/lcd/stm32_lcd.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32_lcd.o"
#arm-none-eabi-gcc "STM32/BSP/Components/st7789h2/st7789h2.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/st7789h2.o"
#arm-none-eabi-gcc "STM32/BSP/Components/st7789h2/st7789h2_reg.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/st7789h2_reg.o"
#arm-none-eabi-gcc "STM32/BSP/Components/ft6x06/ft6x06.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/ft6x06.o"
#arm-none-eabi-gcc "STM32/BSP/Components/ft6x06/ft6x06_reg.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/ft6x06_reg.o"
#arm-none-eabi-gcc "STM32/sysmem.c" ${INC} -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/sysmem.o"
arm-none-eabi-g++ "main.cpp" ${INC} -fno-common -fno-exceptions -fno-rtti -fno-threadsafe-statics -Wno-psabi -mcpu=cortex-m33 -std=c++17 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/main.o"

arm-none-eabi-gcc -mcpu=cortex-m33 -g3 -DDEBUG -c -x assembler-with-cpp -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/startup_stm32h573iikxq.o" "STM32/startup_stm32h573iikxq.s"
OBJS="build/main.o build/startup_stm32h573iikxq.o build/stm32h573i_discovery.o build/stm32h5xx_hal.o build/stm32h5xx_hal_cortex.o build/stm32h5xx_hal_dma.o build/stm32h5xx_hal_dma_ex.o build/stm32h5xx_hal_exti.o build/stm32h5xx_hal_flash.o build/stm32h5xx_hal_flash_ex.o build/stm32h5xx_hal_gpio.o build/stm32h5xx_hal_icache.o build/stm32h5xx_hal_pwr.o build/stm32h5xx_hal_pwr_ex.o build/stm32h5xx_hal_rcc.o build/stm32h5xx_hal_rcc_ex.o build/system_stm32h5xx.o build/stm32h573i_discovery_lcd.o build/stm32h573i_discovery_ts.o build/stm32_lcd.o build/stm32h5xx_hal_sram.o build/stm32h5xx_ll_fmc.o build/st7789h2.o build/st7789h2_reg.o build/ft6x06.o build/ft6x06_reg.o build/stm32h573i_discovery_bus.o build/stm32h5xx_hal_i2c.o build/stm32h5xx_hal_i2c_ex.o build/sysmem.o"
arm-none-eabi-gcc ${OBJS} -o "build/GPIO_IOToggle.elf" -mcpu=cortex-m33 -T"STM32/STM32H573IIKXQ_FLASH.ld" --specs=nosys.specs -Wl,--gc-sections -static --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -Wl,--end-group
./flash.sh