// VTable Address: 0x1003c404 Class: std::bad_alloc (Base Classes: std::exception) (2 virtual functions)
// VTable Address: 0x1003c410 Class: std::locale::facet (1 virtual functions)
// VTable Address: 0x1003c418 Class: std::locale::_Locimp (Base Classes: std::locale::facet) (1 virtual functions)
// VTable Address: 0x1003c428 Class: std::logic_error (Base Classes: std::exception) (2 virtual functions)
// VTable Address: 0x1003c434 Class: std::length_error (Base Classes: std::logic_error std::exception) (2 virtual functions)
// VTable Address: 0x1003c440 Class: std::out_of_range (Base Classes: std::logic_error std::exception) (2 virtual functions)
// VTable Address: 0x1003c504 Class: type_info (1 virtual functions)
// VTable Address: 0x1003c50c Class: std::exception (2 virtual functions)
// VTable Address: 0x1003c52c Class: std::bad_cast (Base Classes: std::exception) (2 virtual functions)
// VTable Address: 0x1003c538 Class: std::bad_typeid (Base Classes: std::exception) (2 virtual functions)
// VTable Address: 0x1003c544 Class: std::__non_rtti_object (Base Classes: std::bad_typeid std::exception) (2 virtual functions)
// VTable Address: 0x1003c698 Class: std::bad_exception (Base Classes: std::exception) (2 virtual functions)
// VTable Address: 0x1003e89c Class: TextLabel (Base Classes: VSTGUI::CTextLabel VSTGUI::CParamDisplay VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x1003ea0c Class: TextEdit (Base Classes: VSTGUI::CTextEdit VSTGUI::CParamDisplay VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x1003eb8c Class: OptionMenu (Base Classes: VSTGUI::COptionMenu VSTGUI::CParamDisplay VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x1003edbc Class: CControlListener (5 virtual functions)
// VTable Address: 0x1003edd4 Class: Editor (Base Classes: TooltipEditor AEffGUIEditor AEffEditor VSTGUI::STGUIEditorInterface CControlListener) (15 virtual functions)
// VTable Address: 0x1003ee14 Class: Editor (Base Classes: TooltipEditor AEffGUIEditor AEffEditor VSTGUI::STGUIEditorInterface CControlListener) (5 virtual functions)
// VTable Address: 0x1003ee2c Class: Editor (Base Classes: TooltipEditor AEffGUIEditor AEffEditor VSTGUI::STGUIEditorInterface CControlListener) (5 virtual functions)
// VTable Address: 0x1003f140 Class: std::ios_base (Base Classes: std::_Iosb<int>) (1 virtual functions)
// VTable Address: 0x1003f148 Class: std::basic_ios<char, std::char_traits<char>> (Base Classes: std::ios_base std::_Iosb<int>) (1 virtual functions)
// VTable Address: 0x1003f150 Class: std::basic_streambuf<char, std::char_traits<char>> (14 virtual functions)
// VTable Address: 0x1003f18c Class: std::basic_istream<char, std::char_traits<char>> (Base Classes: std::basic_ios<char, std::char_traits<char>> std::ios_base std::_Iosb<int>) (1 virtual functions)
// VTable Address: 0x1003f194 Class: std::basic_ostream<char, std::char_traits<char>> (Base Classes: std::basic_ios<char, std::char_traits<char>> std::ios_base std::_Iosb<int>) (1 virtual functions)
// VTable Address: 0x1003f19c Class: std::basic_filebuf<char, std::char_traits<char>> (Base Classes: std::basic_streambuf<char, std::char_traits<char>>) (14 virtual functions)
// VTable Address: 0x1003f1d8 Class: std::basic_ifstream<char, std::char_traits<char>> (Base Classes: std::basic_istream<char, std::char_traits<char>> std::basic_ios<char, std::char_traits<char>> std::ios_base std::_Iosb<int>) (1 virtual functions)
// VTable Address: 0x1003f1e8 Class: std::basic_ofstream<char, std::char_traits<char>> (Base Classes: std::basic_ostream<char, std::char_traits<char>> std::basic_ios<char, std::char_traits<char>> std::ios_base std::_Iosb<int>) (1 virtual functions)
// VTable Address: 0x1003f1f0 Class: std::runtime_error (Base Classes: std::exception) (2 virtual functions)
// VTable Address: 0x1003f1fc Class: std::ctype<char> (Base Classes: std::ctype_base std::locale::facet) (11 virtual functions)
// VTable Address: 0x1003f22c Class: std::ios_base::failure (Base Classes: std::runtime_error std::exception) (2 virtual functions)
// VTable Address: 0x1003f238 Class: std::codecvt<char, char, int> (Base Classes: std::codecvt_base std::locale::facet) (8 virtual functions)
// VTable Address: 0x1003f404 Class: Plugin (Base Classes: AudioEffectX AudioEffect) (64 virtual functions)
// VTable Address: 0x1003f7a4 Class: std::basic_iostream<char, std::char_traits<char>> (Base Classes: std::basic_istream<char, std::char_traits<char>> std::basic_ios<char, std::char_traits<char>> std::ios_base std::_Iosb<int> std::basic_ostream<char, std::char_traits<char>> std::basic_ios<char, std::char_traits<char>> std::ios_base std::_Iosb<int>) (1 virtual functions)
// VTable Address: 0x1003f7ac Class: basic_stringbuf<char, std::char_traits<char>, 2::allocator<char>, ?, ?, ?> (Base Classes: std::basic_streambuf<char, std::char_traits<char>>) (14 virtual functions)
// VTable Address: 0x1003f7e8 Class: basic_stringstream<char, std::char_traits<char>, 2::allocator<char>, ?, ?, ?> (Base Classes: std::basic_iostream<char, std::char_traits<char>> std::basic_istream<char, std::char_traits<char>> std::basic_ios<char, std::char_traits<char>> std::ios_base std::_Iosb<int> std::basic_ostream<char, std::char_traits<char>> std::basic_ios<char, std::char_traits<char>> std::ios_base std::_Iosb<int>) (1 virtual functions)
// VTable Address: 0x1003f800 Class: std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char>>> (Base Classes: std::locale::facet) (9 virtual functions)
// VTable Address: 0x1003f828 Class: std::numpunct<char> (Base Classes: std::locale::facet) (6 virtual functions)
// VTable Address: 0x1003f864 Class: TooltipKnob (Base Classes: VSTGUI::CAnimKnob VSTGUI::CKnob VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject VSTGUI::IMultiBitmapControl) (64 virtual functions)
// VTable Address: 0x1003f9dc Class: TooltipKnob (Base Classes: VSTGUI::CAnimKnob VSTGUI::CKnob VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject VSTGUI::IMultiBitmapControl) (4 virtual functions)
// VTable Address: 0x1003f9f4 Class: TooltipSlider (Base Classes: VSTGUI::CVerticalSlider VSTGUI::CSlider VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x1003fb5c Class: TooltipDisplay (Base Classes: VSTGUI::CParamDisplay VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x1003fcc4 Class: TooltipEditor (Base Classes: AEffGUIEditor AEffEditor VSTGUI::STGUIEditorInterface CControlListener) (15 virtual functions)
// VTable Address: 0x1003fd04 Class: TooltipEditor (Base Classes: AEffGUIEditor AEffEditor VSTGUI::STGUIEditorInterface CControlListener) (5 virtual functions)
// VTable Address: 0x1003fd1c Class: TooltipEditor (Base Classes: AEffGUIEditor AEffEditor VSTGUI::STGUIEditorInterface CControlListener) (5 virtual functions)
// VTable Address: 0x1003fd44 Class: AudioEffect (50 virtual functions)
// VTable Address: 0x1003fe10 Class: AEffEditor (11 virtual functions)
// VTable Address: 0x1003fe40 Class: VSTGUI::STGUIEditorInterface (5 virtual functions)
// VTable Address: 0x1003fe58 Class: AEffGUIEditor (Base Classes: AEffEditor VSTGUI::STGUIEditorInterface) (13 virtual functions)
// VTable Address: 0x1003fe90 Class: AEffGUIEditor (Base Classes: AEffEditor VSTGUI::STGUIEditorInterface) (5 virtual functions)
// VTable Address: 0x1003ff24 Class: VSTGUI::CControl (Base Classes: VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x10040058 Class: VSTGUI::CBaseObject (4 virtual functions)
// VTable Address: 0x1004006c Class: VSTGUI::IMultiBitmapControl (4 virtual functions)
// VTable Address: 0x10040084 Class: VSTGUI::CParamDisplay (Base Classes: VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x100401ec Class: VSTGUI::CTextLabel (Base Classes: VSTGUI::CParamDisplay VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x1004035c Class: VSTGUI::CTextEdit (Base Classes: VSTGUI::CParamDisplay VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x100404dc Class: VSTGUI::COptionMenu (Base Classes: VSTGUI::CParamDisplay VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x10040688 Class: VSTGUI::CMenuItem (Base Classes: VSTGUI::CBaseObject) (12 virtual functions)
// VTable Address: 0x100406bc Class: VSTGUI::CKnob (Base Classes: VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x10040834 Class: VSTGUI::CAnimKnob (Base Classes: VSTGUI::CKnob VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject VSTGUI::IMultiBitmapControl) (64 virtual functions)
// VTable Address: 0x100409ac Class: VSTGUI::CAnimKnob (Base Classes: VSTGUI::CKnob VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject VSTGUI::IMultiBitmapControl) (4 virtual functions)
// VTable Address: 0x100409c4 Class: VSTGUI::CSlider (Base Classes: VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x10040b2c Class: VSTGUI::CKickButton (Base Classes: VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject VSTGUI::IMultiBitmapControl) (64 virtual functions)
// VTable Address: 0x10040c60 Class: VSTGUI::CKickButton (Base Classes: VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject VSTGUI::IMultiBitmapControl) (4 virtual functions)
// VTable Address: 0x10040c74 Class: VSTGUI::CSplashScreen (Base Classes: VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject CControlListener) (64 virtual functions)
// VTable Address: 0x10040db4 Class: VSTGUI::CSplashScreen (Base Classes: VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject CControlListener) (5 virtual functions)
// VTable Address: 0x10040dcc Class: VSTGUI::CDefaultSplashScreenView (Base Classes: VSTGUI::CControl VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x10040fcc Class: VSTGUI::CFrame (Base Classes: VSTGUI::CViewContainer VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x10041164 Class: VSTGUI::CDrawContext (Base Classes: VSTGUI::CBaseObject) (4 virtual functions)
// VTable Address: 0x10041178 Class: VSTGUI::COffscreenContext (Base Classes: VSTGUI::CDrawContext VSTGUI::CBaseObject) (4 virtual functions)
// VTable Address: 0x1004118c Class: VSTGUI::CBitmap (Base Classes: VSTGUI::CBaseObject) (10 virtual functions)
// VTable Address: 0x100411b8 Class: Gdiplus::Brush (Base Classes: Gdiplus::GdiplusBase) (2 virtual functions)
// VTable Address: 0x100411c4 Class: Gdiplus::Bitmap (Base Classes: Gdiplus::Image Gdiplus::GdiplusBase) (2 virtual functions)
// VTable Address: 0x100411d0 Class: Gdiplus::Image (Base Classes: Gdiplus::GdiplusBase) (2 virtual functions)
// VTable Address: 0x100411dc Class: Gdiplus::SolidBrush (Base Classes: Gdiplus::Brush Gdiplus::GdiplusBase) (2 virtual functions)
// VTable Address: 0x100411e8 Class: VSTGUI::CFontDesc (Base Classes: VSTGUI::CBaseObject) (4 virtual functions)
// VTable Address: 0x100411fc Class: VSTGUI::CView (Base Classes: VSTGUI::CBaseObject) (53 virtual functions)
// VTable Address: 0x100412d4 Class: VSTGUI::CViewContainer (Base Classes: VSTGUI::CView VSTGUI::CBaseObject) (64 virtual functions)
// VTable Address: 0x10041400 Class: VSTGUI::GDIPlusGlobals (Base Classes: VSTGUI::CBaseObject) (4 virtual functions)
// VTable Address: 0x10041414 Class: VSTGUI::ResourceStream (Base Classes: IStream ISequentialStream IUnknown) (14 virtual functions)
// VTable Address: 0x10041450 Class: VSTGUI::inDragContainer (Base Classes: VSTGUI::CDragContainer VSTGUI::CBaseObject) (8 virtual functions)
// VTable Address: 0x10041474 Class: VSTGUI::CDropTarget (Base Classes: IDropTarget IUnknown) (8 virtual functions)
