mkdir build
set path=C:\Users\gvalky\Documents\Gabo\Programs\gcc-arm-none-eabi-10.3-2021.10\bin\
set INC=-I STM32H5xx_HAL_Driver\Inc\ -I . -I CMSIS\Core\Include -I STM32
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_cortex.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_cortex.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_dma.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_dma.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_dma_ex.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_dma_ex.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_exti.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_exti.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_flash.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_flash.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_flash_ex.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_flash_ex.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_gpio.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_gpio.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_icache.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_icache.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pwr.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_pwr.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pwr_ex.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_pwr_ex.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rcc.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_rcc.o"
arm-none-eabi-gcc "STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rcc_ex.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_rcc_ex.o"
arm-none-eabi-gcc "STM32/system_stm32h5xx.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/system_stm32h5xx.o"
arm-none-eabi-gcc "STM32/stm32h573i_discovery.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h573i_discovery.o"
arm-none-eabi-gcc "main.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/main.o"
arm-none-eabi-gcc "STM32/stm32h5xx_hal_msp.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_hal_msp.o"
arm-none-eabi-gcc "STM32/stm32h5xx_it.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/stm32h5xx_it.o"
arm-none-eabi-gcc "syscalls.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/syscalls.o"
arm-none-eabi-gcc "sysmem.c" %INC% -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H573xx -c  -O0 -ffunction-sections -fdata-sections -Wall -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/sysmem.o"
arm-none-eabi-gcc -mcpu=cortex-m33 -g3 -DDEBUG -c -x assembler-with-cpp -MMD -MP --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "build/startup_stm32h573iikxq.o" "STM32/startup_stm32h573iikxq.s"
set OBJS=build\main.o build\startup_stm32h573iikxq.o build\stm32h573i_discovery.o build\stm32h5xx_hal.o build\stm32h5xx_hal_cortex.o build\stm32h5xx_hal_dma.o build\stm32h5xx_hal_dma_ex.o build\stm32h5xx_hal_exti.o build\stm32h5xx_hal_flash.o build\stm32h5xx_hal_flash_ex.o build\stm32h5xx_hal_gpio.o build\stm32h5xx_hal_icache.o build\stm32h5xx_hal_msp.o build\stm32h5xx_hal_pwr.o build\stm32h5xx_hal_pwr_ex.o build\stm32h5xx_hal_rcc.o build\stm32h5xx_hal_rcc_ex.o build\stm32h5xx_it.o build\syscalls.o build\sysmem.o build\system_stm32h5xx.o
arm-none-eabi-gcc %OBJS% -o "build\GPIO_IOToggle.elf" -mcpu=cortex-m33 -T"STM32H573IIKXQ_FLASH.ld" --specs=nosys.specs -Wl,--gc-sections -static --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -Wl,--end-group
